# Generated by Django 4.2.1 on 2023-08-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='des',
        ),
    ]
