# Generated by Django 4.2.1 on 2023-08-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_rename_description_post_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='des',
            field=models.CharField(max_length=5000),
        ),
    ]
